In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [3]:
df.columns

Index(['PassengerId', 'Name', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='object')

In [4]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'], axis='columns', inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [6]:
df.isna().sum()

Pclass        0
Sex           0
Age         177
Fare          0
Survived      0
dtype: int64

In [7]:
df['Age'] = df['Age'].fillna(df.Age.mean())

In [8]:
df.isna().sum()

Pclass      0
Sex         0
Age         0
Fare        0
Survived    0
dtype: int64

In [9]:
dummies = pd.get_dummies(df.Sex)
dummies

     female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [14]:
df = pd.concat([df,dummies], axis=1)
df

     Pclass     Sex        Age     Fare  Survived  female  male
0         3    male  22.000000   7.2500         0       0     1
1         1  female  38.000000  71.2833         1       1     0
2         3  female  26.000000   7.9250         1       1     0
3         1  female  35.000000  53.1000         1       1     0
4         3    male  35.000000   8.0500         0       0     1
..      ...     ...        ...      ...       ...     ...   ...
886       2    male  27.000000  13.0000         0       0     1
887       1  female  19.000000  30.0000         1       1     0
888       3  female  29.699118  23.4500         0       1     0
889       1    male  26.000000  30.0000         1       0     1
890       3    male  32.000000   7.7500         0       0     1

[891 rows x 7 columns]

In [16]:
df.drop(['Sex','male'], axis='columns', inplace=True)
df

     Pclass        Age     Fare  Survived  female
0         3  22.000000   7.2500         0       0
1         1  38.000000  71.2833         1       1
2         3  26.000000   7.9250         1       1
3         1  35.000000  53.1000         1       1
4         3  35.000000   8.0500         0       0
..      ...        ...      ...       ...     ...
886       2  27.000000  13.0000         0       0
887       1  19.000000  30.0000         1       1
888       3  29.699118  23.4500         0       1
889       1  26.000000  30.0000         1       0
890       3  32.000000   7.7500         0       0

[891 rows x 5 columns]

In [17]:
inputs = df.drop('Survived', axis=1)
inputs

     Pclass        Age     Fare  female
0         3  22.000000   7.2500       0
1         1  38.000000  71.2833       1
2         3  26.000000   7.9250       1
3         1  35.000000  53.1000       1
4         3  35.000000   8.0500       0
..      ...        ...      ...     ...
886       2  27.000000  13.0000       0
887       1  19.000000  30.0000       1
888       3  29.699118  23.4500       1
889       1  26.000000  30.0000       0
890       3  32.000000   7.7500       0

[891 rows x 4 columns]

In [18]:
target = df.Survived
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.3)

In [21]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [22]:
model.fit(X_train,y_train)

GaussianNB()

In [23]:
model.score(X_test, y_test)

0.7723880597014925

In [24]:
model.predict_proba(X_test)

array([[9.62946910e-01, 3.70530895e-02],
       [1.61644504e-02, 9.83835550e-01],
       [9.62664648e-01, 3.73353515e-02],
       [9.66858364e-01, 3.31416355e-02],
       [9.31920414e-01, 6.80795860e-02],
       [9.64948748e-01, 3.50512518e-02],
       [9.64316594e-01, 3.56834060e-02],
       [9.66582967e-01, 3.34170331e-02],
       [4.07759320e-01, 5.92240680e-01],
       [9.66958034e-01, 3.30419656e-02],
       [7.44426386e-01, 2.55573614e-01],
       [1.31924714e-02, 9.86807529e-01],
       [3.32322205e-01, 6.67677795e-01],
       [9.27571666e-01, 7.24283343e-02],
       [9.63877926e-01, 3.61220744e-02],
       [9.67205853e-01, 3.27941472e-02],
       [7.45558799e-03, 9.92544412e-01],
       [3.97460688e-01, 6.02539312e-01],
       [7.69895545e-01, 2.30104455e-01],
       [9.66665281e-01, 3.33347187e-02],
       [2.59691791e-04, 9.99740308e-01],
       [8.99391377e-01, 1.00608623e-01],
       [9.66706285e-01, 3.32937146e-02],
       [9.67815883e-01, 3.21841166e-02],
       [7.12025911e-02, 9.28797409e-01],
       [9.25896559e-01, 7.41034411e-02],
       [4.07191121e-01, 5.92808879e-01],
       [3.52705383e-05, 9.99964729e-01],
       [9.66142277e-01, 3.38577229e-02],
       [4.33129528e-44, 1.00000000e+00],
       [9.21043272e-01, 7.89567280e-02],
       [9.63509139e-01, 3.64908611e-02],
       [9.21481811e-01, 7.85181886e-02],
       [2.40139434e-01, 7.59860566e-01],
       [9.65894514e-01, 3.41054862e-02],
       [4.06676729e-01, 5.93323271e-01],
       [1.59121502e-02, 9.84087850e-01],
       [9.66356839e-01, 3.36431613e-02],
       [2.40228418e-01, 7.59771582e-01],
       [8.56253920e-10, 9.99999999e-01],
       [3.76782319e-01, 6.23217681e-01],
       [9.28983530e-01, 7.10164704e-02],
       [9.66848044e-01, 3.31519563e-02],
       [3.14683484e-01, 6.85316516e-01],
       [9.63477132e-01, 3.65228684e-02],
       [9.64289939e-01, 3.57100605e-02],
       [1.67760074e-01, 8.32239926e-01],
       [2.43390618e-01, 7.56609382e-01],
       [3.23660646e-01, 6.76339354e-01],
       [1.84192585e-01, 8.15807415e-01],
       [7.75163243e-01, 2.24836757e-01],
       [1.11615263e-12, 1.00000000e+00],
       [6.72200782e-01, 3.27799218e-01],
       [5.91869867e-01, 4.08130133e-01],
       [2.33106350e-01, 7.66893650e-01],
       [4.11902298e-01, 5.88097702e-01],
       [1.53866245e-02, 9.84613375e-01],
       [9.66122628e-01, 3.38773724e-02],
       [9.66548491e-01, 3.34515090e-02],
       [7.48736982e-05, 9.99925126e-01],
       [2.18916019e-01, 7.81083981e-01],
       [9.27098443e-01, 7.29015572e-02],
       [9.66665281e-01, 3.33347187e-02],
       [9.66944989e-01, 3.30550109e-02],
       [3.19538900e-01, 6.80461100e-01],
       [7.63007022e-01, 2.36992978e-01],
       [6.59334892e-01, 3.40665108e-01],
       [9.65963017e-01, 3.40369830e-02],
       [7.78787604e-01, 2.21212396e-01],
       [4.03838120e-01, 5.96161880e-01],
       [9.43217139e-01, 5.67828614e-02],
       [7.48092936e-02, 9.25190706e-01],
       [9.29584058e-01, 7.04159417e-02],
       [7.57415101e-01, 2.42584899e-01],
       [9.66652420e-01, 3.33475796e-02],
       [1.61460324e-03, 9.98385397e-01],
       [9.55447930e-01, 4.45520701e-02],
       [2.70997417e-02, 9.72900258e-01],
       [9.67281049e-01, 3.27189505e-02],
       [9.64518427e-01, 3.54815735e-02],
       [7.75808747e-01, 2.24191253e-01],
       [9.67351582e-01, 3.26484185e-02],
       [4.03008847e-01, 5.96991153e-01],
       [7.57915718e-01, 2.42084282e-01],
       [3.95796768e-01, 6.04203232e-01],
       [4.07468262e-01, 5.92531738e-01],
       [4.07835636e-01, 5.92164364e-01],
       [3.93114721e-01, 6.06885279e-01],
       [9.64257531e-01, 3.57424691e-02],
       [1.69426477e-01, 8.30573523e-01],
       [3.90372523e-01, 6.09627477e-01],
       [9.67029908e-01, 3.29700919e-02],
       [2.39376541e-01, 7.60623459e-01],
       [7.71319757e-01, 2.28680243e-01],
       [3.86325340e-01, 6.13674660e-01],
       [9.66518423e-01, 3.34815768e-02],
       [9.28457039e-01, 7.15429606e-02],
       [9.26364794e-01, 7.36352056e-02],
       [9.67189170e-01, 3.28108305e-02],
       [3.81376192e-01, 6.18623808e-01],
       [3.88994950e-01, 6.11005050e-01],
       [8.94658062e-01, 1.05341938e-01],
       [9.67162301e-01, 3.28376994e-02],
       [2.46562066e-02, 9.75343793e-01],
       [9.28061373e-01, 7.19386268e-02],
       [9.26457857e-01, 7.35421434e-02],
       [9.66665281e-01, 3.33347187e-02],
       [7.77474287e-01, 2.22525713e-01],
       [8.96950818e-01, 1.03049182e-01],
       [6.03973179e-01, 3.96026821e-01],
       [6.46596953e-05, 9.99935340e-01],
       [5.53836971e-01, 4.46163029e-01],
       [3.86430874e-01, 6.13569126e-01],
       [9.27735038e-01, 7.22649622e-02],
       [9.60865618e-01, 3.91343824e-02],
       [9.56984344e-01, 4.30156563e-02],
       [7.75367255e-01, 2.24632745e-01],
       [9.66535419e-01, 3.34645807e-02],
       [9.66451023e-01, 3.35489773e-02],
       [5.75026489e-01, 4.24973511e-01],
       [9.66319828e-01, 3.36801723e-02],
       [6.49963916e-01, 3.50036084e-01],
       [9.26418703e-01, 7.35812975e-02],
       [6.80097043e-01, 3.19902957e-01],
       [9.65709195e-01, 3.42908051e-02],
       [9.66530160e-01, 3.34698397e-02],
       [4.07900089e-01, 5.92099911e-01],
       [7.04752413e-03, 9.92952476e-01],
       [9.61280379e-01, 3.87196211e-02],
       [9.63424637e-01, 3.65753630e-02],
       [4.09083267e-01, 5.90916733e-01],
       [9.53304202e-01, 4.66957978e-02],
       [1.40956737e-02, 9.85904326e-01],
       [9.66665281e-01, 3.33347187e-02],
       [2.33315061e-01, 7.66684939e-01],
       [9.28906667e-01, 7.10933332e-02],
       [2.42986808e-01, 7.57013192e-01],
       [4.08022713e-01, 5.91977287e-01],
       [9.65346534e-01, 3.46534660e-02],
       [5.33396143e-01, 4.66603857e-01],
       [7.47655744e-01, 2.52344256e-01],
       [2.35026965e-01, 7.64973035e-01],
       [9.30143823e-01, 6.98561769e-02],
       [1.40113318e-01, 8.59886682e-01],
       [9.66345532e-01, 3.36544677e-02],
       [1.98272266e-01, 8.01727734e-01],
       [7.72244825e-01, 2.27755175e-01],
       [3.49147355e-01, 6.50852645e-01],
       [9.62370995e-01, 3.76290047e-02],
       [4.30224780e-02, 9.56977522e-01],
       [9.27676407e-01, 7.23235930e-02],
       [9.67029379e-01, 3.29706208e-02],
       [9.67357027e-01, 3.26429726e-02],
       [2.42365907e-01, 7.57634093e-01],
       [9.66531045e-01, 3.34689550e-02],
       [9.51480433e-01, 4.85195672e-02],
       [9.66712651e-01, 3.32873493e-02],
       [2.28181215e-01, 7.71818785e-01],
       [4.06476936e-05, 9.99959352e-01],
       [4.09043780e-01, 5.90956220e-01],
       [9.66626928e-01, 3.33730716e-02],
       [9.63417676e-01, 3.65823237e-02],
       [9.67352339e-01, 3.26476614e-02],
       [4.01980554e-01, 5.98019446e-01],
       [4.05598433e-01, 5.94401567e-01],
       [1.00433116e-12, 1.00000000e+00],
       [9.66665281e-01, 3.33347187e-02],
       [9.63098375e-01, 3.69016247e-02],
       [9.28850373e-01, 7.11496267e-02],
       [9.63763782e-01, 3.62362177e-02],
       [9.28943622e-01, 7.10563776e-02],
       [9.66815806e-01, 3.31841935e-02],
       [9.66694591e-01, 3.33054089e-02],
       [3.18605684e-01, 6.81394316e-01],
       [1.56452312e-02, 9.84354769e-01],
       [9.66694591e-01, 3.33054089e-02],
       [9.66694591e-01, 3.33054089e-02],
       [3.00562167e-05, 9.99969944e-01],
       [9.23996405e-01, 7.60035945e-02],
       [9.67035212e-01, 3.29647881e-02],
       [9.64546411e-01, 3.54535892e-02],
       [4.12936775e-01, 5.87063225e-01],
       [1.60427130e-02, 9.83957287e-01],
       [9.49663900e-01, 5.03361003e-02],
       [9.66535419e-01, 3.34645807e-02],
       [7.70819449e-01, 2.29180551e-01],
       [9.66694591e-01, 3.33054089e-02],
       [8.94099296e-01, 1.05900704e-01],
       [9.67338253e-01, 3.26617472e-02],
       [1.08987433e-02, 9.89101257e-01],
       [9.66965103e-01, 3.30348973e-02],
       [3.92364850e-01, 6.07635150e-01],
       [4.79022654e-02, 9.52097735e-01],
       [4.10641047e-02, 9.58935895e-01],
       [2.43532975e-01, 7.56467025e-01],
       [2.85126836e-05, 9.99971487e-01],
       [4.12567053e-01, 5.87432947e-01],
       [1.75548509e-01, 8.24451491e-01],
       [9.30930024e-01, 6.90699756e-02],
       [3.83799499e-01, 6.16200501e-01],
       [9.67068161e-01, 3.29318387e-02],
       [4.02481034e-01, 5.97518966e-01],
       [4.12047496e-01, 5.87952504e-01],
       [3.15322248e-01, 6.84677752e-01],
       [9.65020378e-01, 3.49796224e-02],
       [9.66636968e-01, 3.33630323e-02],
       [9.40850101e-03, 9.90591499e-01],
       [8.77279808e-01, 1.22720192e-01],
       [3.87045244e-01, 6.12954756e-01],
       [9.65630244e-01, 3.43697564e-02],
       [4.08313119e-01, 5.91686881e-01],
       [4.09082439e-01, 5.90917561e-01],
       [4.77139514e-02, 9.52286049e-01],
       [7.77153845e-01, 2.22846155e-01],
       [9.66838898e-01, 3.31611023e-02],
       [2.17239471e-01, 7.82760529e-01],
       [9.67386373e-01, 3.26136268e-02],
       [9.62874210e-01, 3.71257897e-02],
       [9.56666767e-01, 4.33332331e-02],
       [1.73391349e-01, 8.26608651e-01],
       [4.16624803e-01, 5.83375197e-01],
       [7.75163243e-01, 2.24836757e-01],
       [6.67614269e-01, 3.32385731e-01],
       [9.67347431e-01, 3.26525692e-02],
       [9.66535419e-01, 3.34645807e-02],
       [2.26646051e-01, 7.73353949e-01],
       [9.67068161e-01, 3.29318387e-02],
       [8.95057896e-10, 9.99999999e-01],
       [9.67358254e-01, 3.26417459e-02],
       [2.17239471e-01, 7.82760529e-01],
       [9.67061066e-01, 3.29389336e-02],
       [9.65498506e-01, 3.45014935e-02],
       [9.31817903e-01, 6.81820966e-02],
       [9.66636968e-01, 3.33630323e-02],
       [9.60132030e-01, 3.98679697e-02],
       [4.07523205e-01, 5.92476795e-01],
       [4.07656399e-01, 5.92343601e-01],
       [1.26498569e-08, 9.99999987e-01],
       [7.72087864e-01, 2.27912136e-01],
       [9.64341917e-01, 3.56580834e-02],
       [9.58161973e-01, 4.18380272e-02],
       [9.67091487e-01, 3.29085132e-02],
       [9.65932666e-01, 3.40673335e-02],
       [3.27663343e-01, 6.72336657e-01],
       [9.62028187e-01, 3.79718126e-02],
       [4.04519774e-11, 1.00000000e+00],
       [9.64714698e-01, 3.52853022e-02],
       [9.67774683e-01, 3.22253166e-02],
       [4.12927113e-01, 5.87072887e-01],
       [7.43566922e-01, 2.56433078e-01],
       [9.66821054e-01, 3.31789456e-02],
       [4.07170576e-01, 5.92829424e-01],
       [9.64416721e-01, 3.55832787e-02],
       [9.66531045e-01, 3.34689550e-02],
       [6.34929625e-01, 3.65070375e-01],
       [7.26575610e-01, 2.73424390e-01],
       [9.63900046e-01, 3.60999543e-02],
       [9.66372913e-01, 3.36270868e-02],
       [3.64855566e-01, 6.35144434e-01],
       [6.22781727e-02, 9.37721827e-01],
       [1.73391349e-01, 8.26608651e-01],
       [9.65525683e-01, 3.44743171e-02],
       [9.66636968e-01, 3.33630323e-02],
       [9.66804599e-01, 3.31954006e-02],
       [3.90338840e-01, 6.09661160e-01],
       [9.66531045e-01, 3.34689550e-02],
       [3.09008336e-01, 6.90991664e-01],
       [8.21878506e-04, 9.99178121e-01]])

In [31]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train,y_train,cv=5)

array([0.744     , 0.752     , 0.784     , 0.81451613, 0.80645161])